=== snsk7/clzlab/test/test.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT root (child+) >
<!ELEMENT child (name,address,age) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT address (#PCDATA) >
<!ELEMENT age (#PCDATA) >

<!ATTLIST child aid CDATA #REQUIRED>

=== snsk7/clzlab/test/test.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE root SYSTEM "./test.dtd" >

<root>
    <child aid="1">
        <name>ccer</name>
        <address>bagamra</address>
        <age>21</age>
    </child>
    <child aid="2">
        <name>shadbhav</name>
        <address>naya bazar</address>
        <age>18</age>
    </child>
</root>
