<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE root[
    <!ELEMENT root (child+)>
    <!ELEMENT child (name,age,address,contact)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT address (#PCDATA)>
    <!ELEMENT contact (#PCDATA)>
    <!ATTLIST name aid CDATA #IMPLIED>
]>

<root>
    <child>
        <name aid="2">ccer</name>
        <age>21</age>
        <address>bagmara</address>
        <contact>9815179012</contact>
    </child>
    <child>
        <name aid="1">arpan</name>
        <age>30</age>
        <address>us-txs</address>
        <contact>00000000</contact>
    </child>
</root>